name: Build and Push tiny PKI Root Docker Image

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - 
        name: Check out code
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            deleteonerror/tinypki_root
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,format=long
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.ref }}
            org.opencontainers.image.vendor=Delete on error
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.title=Tiny PKI Root CA
            org.opencontainers.image.description=The Root CA of the `tiny PKI` project. Providing a PKI for Home, Lab and Dev usage.
            org.opencontainers.image.documentation=https://github.com/deleteonerror/tinyPKI/blob/main/docs/setup.md
            org.label-schema.docker.params=TINY_ROOT_PATH=optional Data Directory, TINY_LOG=Info
            org.opencontainers.image.authors=silvio <info@deleteonerror.com>"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_DELETEONERROR_RW }}
      -
        name: Build and push Tiny PKI Root Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./build/Dockerfile-tpkiroot
          platforms: linux/amd64,linux/arm64
          sbom: ${{ github.event_name != 'pull_request' }}
          provenance: ${{ github.event_name != 'pull_request' }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
